"""Per-setlist song recommendation, generated by a background task."""

from datetime import datetime
from enum import StrEnum
from uuid import UUID, uuid4

from sqlalchemy import Column, DateTime, func
from sqlmodel import Field, SQLModel


class RecommendationStatus(StrEnum):
    """Lifecycle of a setlist's recommendation."""

    PENDING = "pending"
    READY = "ready"
    NOT_FOUND = "not_found"
    FAILED = "failed"


class RecommendationBase(SQLModel):
    """
    The recommended song, shaped like a Discogs search result so the client
    can add it through the same POST /songs flow as a search result. It is
    deliberately not a Song row: songs are global, and an unadopted
    recommendation would linger in the catalog.
    """

    title: str | None = Field(default=None, max_length=255)
    artist: str | None = Field(default=None, max_length=255)
    album: str | None = Field(default=None, max_length=255)
    release_year: int | None = Field(default=None)
    duration_ms: int | None = Field(default=None)
    thumbnail: str | None = Field(default=None, max_length=512)
    discogs_id: str | None = Field(default=None, max_length=255)
    discogs_url: str | None = Field(default=None, max_length=512)


class SetlistRecommendation(RecommendationBase, table=True):
    """Database model holding the current recommendation for one setlist."""

    __tablename__ = "setlist_recommendations"

    setlist_id: UUID = Field(foreign_key="setlists.id", primary_key=True, ondelete="CASCADE")
    status: str = Field(max_length=20)
    # Replaced on every request; a background run only saves its result if
    # it is still the latest request (see src/tasks/recommendations.py).
    request_id: UUID = Field(default_factory=uuid4)
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now()),
    )


class RecommendationRead(RecommendationBase):
    """Response schema for a setlist's recommendation."""

    status: RecommendationStatus
