"""add setlist recommendations

Revision ID: 64a547103200
Revises: 2bec78361481
Create Date: 2026-10-09 10:51:50.692744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64a547103200'
down_revision: Union[str, Sequence[str], None] = '2bec78361481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setlist_recommendations',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('album', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('discogs_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('discogs_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('setlist_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['setlist_id'], ['setlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('setlist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setlist_recommendations')
    # ### end Alembic commands ###
